version: "1"
run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - gofmt
    - goimports
    - errcheck
    - ineffassign
    - staticcheck
    - gosimple
    - unused
    - typecheck
    - structcheck
    - deadcode
    - varcheck
    - misspell
    - gocritic

  disable:
    - depguard # sometimes too restrictive for small projects

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
  fix: false
  uniq-by-line: true
  whole-files: true

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
      colors: true
